### ISSUE TITLE
Physics objects flying to 0,0,0 coordinate space

### ISSUE THREAD

**Issue by chasester** [chasester/Rival3dengine#14]
On reloading a map some times objects will fly (very quickly) towards the 0,0,0 coordinate. To fix simply save the map (if there are changes) type /disconnect in to the command line. Then reload the map. This seems to be do to left over energy from bullet not being stopped correctly. Will fix in the future.

**Comment by api-Hypernova** [comment]
Bugs like this would be a great way to open development to the community :) You could make a post on Tesseract forums or other looking for volunteers.

**Comment by chasester** [comment]
I know why it exist. Kinda its cuz of the sloppy nature of the bullet angelscript link. This will be fixed when I round out this section. Its really a one off error that happens maybe once in every 100th time. Mostly cuz i have the "n" key bound to sleep 10 [ edittoggle; newasent object; savemap; map untitled; ] this is done for debug reasons but this gives little to no time for angelscript to run the first frame cycle which is where this error occurs. It hasn't occurred in any normal saving or loading of the map. I will add some small issues and objective on here. Like basic function linking, and cube script rewrites of some of the menu cube etc. But I dont see much people looking for work to do, so until i get interested there isn't much reason to outline such project. If you know of people interested I can find things that need done and give them details on exactly how to implement said change :)

Im very big about documenting any, even minute one off case bugs so i dont forget and can look at them later, or see if they where resolved incidentally

chasester

**Comment by chasester** [comment]
Found this a while ago, was dude to a velocity error I think, if you see this error again reopen this ticket.
