### ISSUE TITLE
Object model files 

### ISSUE THREAD

**Issue by chasester** [chasester/Rival3dengine#15]
Git ignore ignores *.obj files which was intented to ignore the obj files created by vs. This also removes all the object model files in tesseract base. This creates an error in attach model() To fix add models from the main tesseract build. This will be later changed so that vs release and debug folders are ignored instead of all *obj files.

**Comment by AndyM84** [comment]
Have you considered adopting something along the lines of CMake so you can normalize where your produced binaries are stored and instead add that location to the .gitignore?

**Comment by chasester** [comment]
I have not I'm very much a github noob. I'm use to svn where i cant click and ignore files and folders. So what I assume you mean is making .gitignore files in localized areas of the code base so only the sub directories are effected by this .gitignore, rather then making all of them global?

**Comment by chasester** [comment]
Fix a while ago along with other content errors.
